# Generated by Django 3.2.9 on 2021-11-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schools', '0002_alter_school_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_schools.school')),
            ],
        ),
    ]
